apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: guestbook
  labels:
    app: guestbook-6-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-6-1
  template:
    metadata:
      name: guestbook
      labels:
        app: guestbook-6-1
    spec:
      containers:
        - name: guestbook
          image: ghcr.io/cloudowski/flask-guestbook:0.1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet: 
              path: /healthz
              port: 8080
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 15
