apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-8-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-8-1
  template:
    metadata:
      labels:
        app: guestbook-8-1
    spec:
      containers:
      - name: guestbook-8-1
        image: ghcr.io/cloudowski/flask-guestbook:0.1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 15