apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
  - name: nginx
    image: nginx:1.22
    volumeMounts:
      - mountPath: /app/config
        name: config-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
  - name: config-volume
    configMap:
      name: appconfig
