apiVersion: v1
kind: Pod
metadata:
  name: postgres-4-1
  labels:
    name: postgres-4-1
spec:
  containers:
  - name: postgres
    image: docker.io/postgres:15-bullseye
    env:
      - name: POSTGRES_PASSWORD
        value: 
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: dbdata
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: dbdata
      persistentVolumeClaim:
        claimName: dbvol
