apiVersion: v1
kind: Pod
metadata:
  name: postgres-5-1
  labels:
    app: postgres-5-1
spec:
  containers:
  - name: postgres
    image: docker.io/postgres:15-bullseye
    env:
      - name: POSTGRES_PASSWORD
        value: P4ssw0rd!
      - name: POSTGRES_DB
        value: flask
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: dbdata
  volumes:
    - name: dbdata
      persistentVolumeClaim:
        claimName: dbvol-5-1
