apiVersion: v1
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  localhost;
        location / {
            proxy_pass          http://backend:8000;
            proxy_http_version  1.1;
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: proxy
  name: proxy-cm0
