apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
    spec:
      containers:
        - name: app
          image: nginx:1.22
          ports:
            - containerPort: 80
              name: http
