apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: guestbook-3-1
  labels:
    app: guestbook-3-1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: guestbook-3-1
  template:
    metadata:
      labels:
        app: guestbook-3-1
    spec:
      containers:
        - name: guestbook
          image: ghcr.io/cloudowski/flask-guestbook:0.1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
